import type { Report } from "./types";

const daysAgo = (d: number) =>
  new Date(Date.now() - d * 86400000).toISOString();

/** Michigan demo reports — used when Convex is not configured */
export const SEED_REPORTS: Report[] = [
  {
    id: "r1",
    product_type: "flower",
    brand_name: "Common Citizen",
    dispensary_name: "Greenhouse of Walled Lake",
    city: "Warren",
    strain_name: "Garlic Breath",
    price_paid: 45,
    package_date: "2025-11-02",
    issue_tags: ["Dry", "No Flavor", "Overpriced / Taxed"],
    boof_score: 2,
    notes: "Community report: dry buds, muted terps, felt overpriced for tier.",
    latitude: 42.5145,
    longitude: -83.0147,
    confirm_count: 12,
    downvote_count: 1,
    created_at: daysAgo(1),
  },
  {
    id: "r2",
    product_type: "cart",
    brand_name: "Platinum Vape",
    dispensary_name: "Exclusive Ann Arbor",
    city: "Ann Arbor",
    strain_name: "Blue Dream Cart",
    price_paid: 25,
    package_date: "2025-12-10",
    issue_tags: ["Leaking Cart", "Weak High"],
    boof_score: 1.5,
    notes: "Reported leaking hardware and weak effects.",
    latitude: 42.2808,
    longitude: -83.743,
    confirm_count: 28,
    downvote_count: 2,
    created_at: daysAgo(0.5),
  },
  {
    id: "r3",
    product_type: "flower",
    brand_name: "Grown Rogue",
    dispensary_name: "The Woods",
    city: "Ferndale",
    strain_name: "Jealousy",
    price_paid: 38,
    package_date: "2026-01-15",
    issue_tags: [],
    boof_score: 5,
    notes: "Community fire find — loud nose, clean burn, strong reported effects.",
    latitude: 42.4606,
    longitude: -83.1346,
    confirm_count: 45,
    downvote_count: 0,
    created_at: daysAgo(2),
  },
  {
    id: "r4",
    product_type: "pre-roll",
    brand_name: "Dogwalkers",
    dispensary_name: "House of Dank",
    city: "Detroit",
    strain_name: "Super Boof PR",
    price_paid: 12,
    package_date: "2025-10-20",
    issue_tags: ["Old Package Date", "Harsh Smoke"],
    boof_score: 2.5,
    notes: "Possible stale package date per community report.",
    latitude: 42.3314,
    longitude: -83.0458,
    confirm_count: 8,
    downvote_count: 3,
    created_at: daysAgo(3),
  },
  {
    id: "r5",
    product_type: "flower",
    brand_name: "Peninsula Gardens",
    dispensary_name: "Lume Cannabis",
    city: "Bay City",
    strain_name: "Gelato 41",
    price_paid: 50,
    package_date: "2026-02-01",
    issue_tags: ["Mold"],
    boof_score: 1,
    notes: "Possible mold concern reported — inspect product yourself.",
    latitude: 43.5945,
    longitude: -83.8889,
    confirm_count: 19,
    downvote_count: 1,
    created_at: daysAgo(1.5),
  },
  {
    id: "r6",
    product_type: "disposable",
    brand_name: "Mitten Extracts",
    dispensary_name: "Puff Cannabis",
    city: "Hazel Park",
    strain_name: "Mango Haze Disposable",
    price_paid: 30,
    package_date: "2026-01-28",
    issue_tags: ["Overpriced / Taxed", "Fake Sale"],
    boof_score: 2,
    notes: "Reported fake sale pricing vs shelf tag.",
    latitude: 42.5125,
    longitude: -83.1041,
    confirm_count: 22,
    downvote_count: 4,
    created_at: daysAgo(0.8),
  },
  {
    id: "r7",
    product_type: "concentrate",
    brand_name: "Element",
    dispensary_name: "Zen Leaf",
    city: "Port Huron",
    strain_name: "Live Rosin — GMO",
    price_paid: 55,
    package_date: "2026-02-10",
    issue_tags: ["CRC Garbage"],
    boof_score: 2,
    notes: "Community report questions CRC processing quality.",
    latitude: 42.9709,
    longitude: -82.4249,
    confirm_count: 15,
    downvote_count: 6,
    created_at: daysAgo(4),
  },
  {
    id: "r8",
    product_type: "flower",
    brand_name: "Fresh Coast",
    dispensary_name: "Skymint",
    city: "Detroit",
    strain_name: "Runtz",
    price_paid: 42,
    package_date: "2026-02-20",
    issue_tags: [],
    boof_score: 4.5,
    notes: "Solid community find — good nose and reported smooth smoke.",
    latitude: 42.348,
    longitude: -83.06,
    confirm_count: 31,
    downvote_count: 2,
    created_at: daysAgo(0.3),
  },
  {
    id: "r9",
    product_type: "edible",
    brand_name: "Wyld",
    dispensary_name: "Apothecare",
    city: "Ann Arbor",
    strain_name: "Marionberry Gummies",
    price_paid: 18,
    package_date: "2026-01-05",
    issue_tags: ["Weak High"],
    boof_score: 3,
    notes: "Reported weaker than expected effects at listed dose.",
    latitude: 42.275,
    longitude: -83.75,
    confirm_count: 6,
    downvote_count: 2,
    created_at: daysAgo(5),
  },
  {
    id: "r10",
    product_type: "cart",
    brand_name: "Redbud Roots",
    dispensary_name: "Botaniq",
    city: "Ferndale",
    strain_name: "MAC Cart 1g",
    price_paid: 35,
    package_date: "2026-02-15",
    issue_tags: [],
    boof_score: 4.8,
    notes: "Fire cart per multiple community confirmations.",
    latitude: 42.458,
    longitude: -83.128,
    confirm_count: 38,
    downvote_count: 1,
    created_at: daysAgo(1.2),
  },
  {
    id: "r11",
    product_type: "flower",
    brand_name: "Society C",
    dispensary_name: "Plan B Wellness",
    city: "Detroit",
    strain_name: "Ice Cream Cake",
    price_paid: 55,
    package_date: "2025-09-01",
    issue_tags: ["Seeds/Stems", "Overpriced / Taxed"],
    boof_score: 2,
    notes: "Reported seeds/stems and taxed pricing for quality tier.",
    latitude: 42.32,
    longitude: -83.08,
    confirm_count: 14,
    downvote_count: 2,
    created_at: daysAgo(6),
  },
  {
    id: "r12",
    product_type: "flower",
    brand_name: "Tymber",
    dispensary_name: "Nirvana Center",
    city: "Warren",
    strain_name: "Permanent Marker",
    price_paid: 40,
    package_date: "2026-02-18",
    issue_tags: ["No Flavor"],
    boof_score: 2.5,
    notes: "Community report: hay smell, little flavor on exhale.",
    latitude: 42.52,
    longitude: -83.03,
    confirm_count: 9,
    downvote_count: 1,
    created_at: daysAgo(2.5),
  },
  {
    id: "r13",
    product_type: "pre-roll",
    brand_name: "High Supply",
    dispensary_name: "Liv",
    city: "Hazel Park",
    strain_name: "Hybrid PR 5-pack",
    price_paid: 28,
    package_date: "2026-01-20",
    issue_tags: [],
    boof_score: 4,
    notes: "Decent value pre-roll pack per community.",
    latitude: 42.51,
    longitude: -83.1,
    confirm_count: 11,
    downvote_count: 0,
    created_at: daysAgo(7),
  },
  {
    id: "r14",
    product_type: "flower",
    brand_name: "Grizzly Peak",
    dispensary_name: "The Reef",
    city: "Detroit",
    strain_name: "Papaya",
    price_paid: 48,
    package_date: "2026-02-05",
    issue_tags: ["Dry"],
    boof_score: 3,
    notes: "Mid tier — reported slightly dry but smokeable.",
    latitude: 42.335,
    longitude: -83.05,
    confirm_count: 5,
    downvote_count: 1,
    created_at: daysAgo(3.5),
  },
  {
    id: "r15",
    product_type: "cart",
    brand_name: "Chill Medicated",
    dispensary_name: "Cloud Cannabis",
    city: "Bay City",
    strain_name: "Strawberry Cough",
    price_paid: 20,
    package_date: "2025-12-01",
    issue_tags: ["Harsh Smoke", "Weak High"],
    boof_score: 2,
    notes: "Harsh hit and weak reported high.",
    latitude: 43.59,
    longitude: -83.89,
    confirm_count: 17,
    downvote_count: 3,
    created_at: daysAgo(4.5),
  },
];
